fs:
  defaultFS: ''
hive:
  hmshandler:
    retry:
      interval: 2000ms
      attempts: '15'
  keytab:
    path: /path/to/keytab/file
    user: xxx@xx.com
  jdbc:
    className: org.apache.hive.jdbc.HiveDriver
    url: jdbc:hive2://localhost:10000;auth=noSasl
  metastore:
    dbname: default
    uris: thrift://localhost:9083
  need:
    kerberos: 'false'
jobInstance:
  fixedDelay:
    in:
      milliseconds: '60000'
  expired:
    milliseconds: '604800000'
spring:
  jpa:
    generate-ddl: 'true'
    show-sql: 'true'
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/mysql_sink?autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
external:
  env:
    location: ''
  config:
    location: ''
predicate:
  job:
    interval: 5m
    repeat:
      count: '12'
ldap:
  searchBase: DC=org,DC=example
  email: '@example.com'
  searchPattern: (sAMAccountName={0})
  url: ldap://hostname:port
login:
  strategy: default
livy:
  task:
    submit:
      interval:
        second: '3'
    max:
      concurrent:
        count: '20'
    appId:
      retry:
        count: '3'
  server:
    auth:
      kerberos:
        principal: livy/kerberos.principal
        keytab: /path/to/livy/keytab/file
  need:
    queue: 'false'
    kerberos: 'false'
  uri: http://localhost:8998/batches
kafka:
  schema:
    registry:
      url: http://localhost:8081
mybatis:
  type-aliases-package: org.apache.griffin.core.entity
  type-handlers-package: org.apache.griffin.core.handler
cache:
  evict:
    hive:
      fixedRate:
        in:
          milliseconds: '900000'
yarn:
  uri: http://localhost:8088
server:
  port: '8090'
elasticsearch:
  host: localhost
  scheme: http
  port: '9200'
logging:
  file: logs/griffin-service.log
internal:
  event:
    listeners: GriffinJobEventHook
